ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.package-comments]
    Disabled = true
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
	Disabled = true
[rule.increment-decrement]
[rule.var-naming]
	Disabled = true
[rule.var-declaration]
	Disabled = true
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
	Disabled = true
[rule.indent-error-flow]
