global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'capataz'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      # Where the capataz example will be running
      - targets: ["app:8080"]
