name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: capatazlib
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      # - run: nix-shell ci.nix --run 'make lint'
      - run: nix-shell ci.nix --run 'go version'
      - run: nix-shell ci.nix --run 'env | grep GO'
      - run: nix-shell ci.nix --run 'make test'
